import type {
  DetectionRule,
  Host,
  Integration,
  Organization,
  ThreatProfile,
  User,
} from "@/lib/domain/types";

/**
 * The fictional organization every demo dataset is generated against.
 * Small enough to explain in one breath at an exhibition stand, detailed
 * enough that the correlation results look like a real environment.
 */

export const HOSTS: Host[] = [
  {
    id: "h-dc01",
    hostname: "DC01",
    ip: "10.20.0.10",
    os: "Windows Server 2022",
    role: "domain-controller",
    criticality: "critical",
    owner: "Infrastructure",
  },
  {
    id: "h-ws01",
    hostname: "WS01",
    ip: "10.20.10.31",
    os: "Windows 11 Enterprise",
    role: "workstation",
    criticality: "high",
    owner: "Finance",
  },
  {
    id: "h-ws02",
    hostname: "WS02",
    ip: "10.20.10.32",
    os: "Windows 11 Enterprise",
    role: "workstation",
    criticality: "medium",
    owner: "Engineering",
  },
  {
    id: "h-caldera01",
    hostname: "CALDERA01",
    ip: "10.20.99.5",
    os: "Ubuntu 22.04 LTS",
    role: "emulation-server",
    criticality: "low",
    owner: "Purple Team",
  },
  {
    id: "h-elastic01",
    hostname: "ELASTIC01",
    ip: "10.20.99.10",
    os: "Ubuntu 22.04 LTS",
    role: "server",
    criticality: "medium",
    owner: "SOC",
  },
];

export const ORGANIZATION: Organization = {
  id: "org-burhan-demo",
  name: "Burhan Demo Enterprise",
  industry: "Financial Services",
  timezone: "UTC",
  hosts: HOSTS,
  targets: {
    mttdSeconds: 60,
    mttaSeconds: 120,
    mttrSeconds: 300,
    mttcSeconds: 600,
    detectionRatePct: 90,
    responseRatePct: 85,
  },
};

export const DEMO_USER: User = {
  id: "u-001",
  name: "Ahmed Muhaisen",
  email: "admin@burhan.local",
  role: "admin",
  title: "SOC Manager",
  initials: "AM",
  organizationId: ORGANIZATION.id,
};

export const THREAT_PROFILES: ThreatProfile[] = [
  {
    id: "apt29",
    name: "APT29",
    aliases: ["Cozy Bear", "Midnight Blizzard", "NOBELIUM"],
    description:
      "State-sponsored espionage actor known for stealthy, credential-centric intrusions, heavy living-off-the-land tradecraft and long dwell times.",
  },
];

/**
 * The SIEM's rule inventory. `enabled: false` is not an accident — a disabled
 * rule is the one coverage gap the correlation engine is built to expose.
 */
export const DETECTION_RULES: DetectionRule[] = [
  {
    id: "ELA-R-0101",
    name: "APT29 - Phishing via HTA and Mshta Proxy Execution",
    siem: "elastic",
    techniqueIds: ["T1566.001", "T1218.005"],
    severity: "high",
    confidence: "high",
    enabled: true,
    dataSources: ["Email Gateway", "Process Creation"],
    description: "HTA attachment opened followed by mshta.exe proxying execution into a script host.",
  },
  {
    id: "ELA-R-0114",
    name: "Encoded PowerShell Command Execution",
    siem: "elastic",
    techniqueIds: ["T1059.001"],
    severity: "high",
    confidence: "high",
    enabled: true,
    dataSources: ["PowerShell Script Block Logging", "Process Creation"],
    description: "PowerShell invoked with -EncodedCommand or heavy obfuscation markers.",
  },
  {
    id: "ELA-R-0130",
    name: "Host Reconnaissance Command Execution",
    siem: "elastic",
    techniqueIds: ["T1082"],
    severity: "low",
    confidence: "medium",
    enabled: true,
    dataSources: ["Process Creation", "Command Line"],
    description: "systeminfo, hostname or wmic executed shortly after initial execution on a host.",
  },
  {
    id: "ELA-R-0133",
    name: "Registry Run Key Persistence",
    siem: "elastic",
    techniqueIds: ["T1547.001"],
    severity: "medium",
    confidence: "high",
    enabled: true,
    dataSources: ["Registry Modification"],
    description: "New autorun value written under a Run or RunOnce key.",
  },
  {
    id: "ELA-R-0138",
    name: "Scheduled Task Creation by Non-Admin Process",
    siem: "elastic",
    techniqueIds: ["T1053.005"],
    severity: "medium",
    confidence: "high",
    enabled: true,
    dataSources: ["Scheduled Job Creation", "Windows Event 4698"],
    description: "schtasks.exe or the Task Scheduler API creating a task from a user process.",
  },
  {
    id: "ELA-R-0145",
    name: "WMI Event Subscription Persistence",
    siem: "elastic",
    techniqueIds: ["T1546.003"],
    severity: "high",
    confidence: "high",
    enabled: true,
    dataSources: ["WMI Activity Log", "Process Creation"],
    description: "A permanent WMI event filter, consumer and binding registered outside change control.",
  },
  {
    id: "ELA-R-0150",
    name: "Cross-Process Injection Detected",
    siem: "elastic",
    techniqueIds: ["T1055"],
    severity: "critical",
    confidence: "high",
    enabled: true,
    dataSources: ["EDR Telemetry", "API Monitoring"],
    description: "Remote thread creation or memory write into a foreign process.",
  },
  {
    id: "ELA-R-0161",
    name: "Security Tooling Disabled",
    siem: "elastic",
    techniqueIds: ["T1562.001"],
    severity: "critical",
    confidence: "high",
    enabled: true,
    dataSources: ["Service Modification", "Registry Modification"],
    description: "Defender, EDR sensor or audit policy disabled on an endpoint.",
  },
  {
    id: "ELA-R-0174",
    name: "Domain Account Enumeration",
    siem: "elastic",
    techniqueIds: ["T1087.002"],
    severity: "medium",
    confidence: "medium",
    enabled: true,
    dataSources: ["Process Creation", "LDAP Query Logs"],
    description: "net group / LDAP enumeration of privileged domain groups.",
  },
  {
    id: "ELA-R-0180",
    name: "LSASS Memory Access",
    siem: "elastic",
    techniqueIds: ["T1003.001"],
    severity: "critical",
    confidence: "high",
    enabled: true,
    dataSources: ["Sysmon Event 10", "EDR Telemetry"],
    description: "Handle opened to lsass.exe with read-memory access rights.",
  },
  {
    id: "ELA-R-0181",
    name: "Registry Hive Export (SAM / SYSTEM)",
    siem: "elastic",
    techniqueIds: ["T1003"],
    severity: "critical",
    confidence: "high",
    // Deliberately off: this is the rule behind the headline coverage gap.
    enabled: false,
    dataSources: ["Process Creation", "File Creation"],
    description:
      "reg.exe save of the SAM, SYSTEM or SECURITY hive. Disabled during noise reduction and never re-enabled.",
  },
  {
    id: "ELA-R-0185",
    name: "Suspicious Directory Replication Service Request (DCSync)",
    siem: "elastic",
    techniqueIds: ["T1003.006"],
    severity: "critical",
    confidence: "high",
    enabled: true,
    dataSources: ["Windows Event 4662", "Directory Service Access Logs"],
    description: "A non-domain-controller account issues DS-Replication-Get-Changes requests to a DC.",
  },
  {
    id: "ELA-R-0190",
    name: "Anomalous Remote Desktop Session",
    siem: "elastic",
    techniqueIds: ["T1021.001"],
    severity: "high",
    confidence: "high",
    enabled: true,
    dataSources: ["Windows Event 4624", "Network Traffic"],
    description: "RDP logon from a workstation to a tier-0 asset outside business hours.",
  },
  {
    id: "ELA-R-0195",
    name: "Non-Standard WinRM Session to Domain Controller",
    siem: "elastic",
    techniqueIds: ["T1021.006"],
    severity: "high",
    confidence: "high",
    enabled: true,
    dataSources: ["Process Creation", "Network Traffic", "WinRM Logs"],
    description: "A WinRM session reaches a domain controller from a host that does not normally do so.",
  },
  {
    id: "ELA-R-0199",
    name: "Bulk File Access via Automated Collection Tooling",
    siem: "elastic",
    techniqueIds: ["T1119"],
    severity: "medium",
    confidence: "medium",
    enabled: true,
    dataSources: ["File Access", "Process Creation"],
    description: "A scripted process reads a high volume of files across sensitive shares in a short window.",
  },
  {
    id: "ELA-R-0208",
    name: "Large Outbound Transfer Over C2 Channel",
    siem: "elastic",
    techniqueIds: ["T1041"],
    severity: "high",
    confidence: "medium",
    enabled: true,
    dataSources: ["Network Traffic", "Web Proxy"],
    description: "Outbound volume anomaly on an established beacon channel.",
  },
  {
    id: "SPL-R-0044",
    name: "Shadow Copy Deletion",
    siem: "splunk",
    techniqueIds: ["T1490"],
    severity: "critical",
    confidence: "high",
    enabled: true,
    dataSources: ["Process Creation", "Command Line"],
    description: "vssadmin, wbadmin or bcdedit invoked to destroy recovery points. Not yet exercised.",
  },
  {
    id: "ELA-R-0215",
    name: "Local Account Created on Endpoint",
    siem: "elastic",
    techniqueIds: ["T1136.001"],
    severity: "medium",
    confidence: "medium",
    enabled: true,
    dataSources: ["Windows Event 4720"],
    description: "New local account created outside of provisioning automation. Not yet exercised.",
  },
];

export const INTEGRATIONS: Integration[] = [
  {
    id: "int-caldera",
    name: "MITRE CALDERA",
    vendor: "MITRE",
    category: "emulation",
    status: "connected",
    apiStatus: "healthy",
    endpoint: "https://caldera01.demo.burhan.local:8888",
    version: "4.2.0",
    description: "Primary adversary emulation platform. Executes the attack side of every validation run.",
    latencyMs: 118,
    adapterId: "caldera",
    configFields: [
      { key: "baseUrl", label: "Server URL", placeholder: "https://caldera01:8888" },
      { key: "apiKey", label: "API key", placeholder: "RED-••••••••", secret: true },
    ],
  },
  {
    id: "int-elastic",
    name: "Elastic Security",
    vendor: "Elastic",
    category: "siem",
    status: "connected",
    apiStatus: "healthy",
    endpoint: "https://elastic.demo.burhan.local:9200",
    version: "8.15",
    description: "Primary SIEM. Burhan reads detection alerts, rule metadata and endpoint telemetry.",
    latencyMs: 87,
    adapterId: "elastic",
    configFields: [
      { key: "baseUrl", label: "Elasticsearch URL", placeholder: "https://elastic:9200" },
      { key: "apiKey", label: "API key", placeholder: "••••••••", secret: true },
    ],
  },
  {
    id: "int-splunk",
    name: "Splunk",
    vendor: "Splunk",
    category: "siem",
    status: "disconnected",
    apiStatus: "unknown",
    endpoint: "",
    version: "—",
    description: "Secondary SIEM adapter for organizations running Splunk Enterprise Security.",
    adapterId: "splunk",
    configFields: [
      { key: "baseUrl", label: "Management URL", placeholder: "https://splunk:8089" },
      { key: "token", label: "Bearer token", placeholder: "••••••••", secret: true },
    ],
  },
  {
    id: "int-sentinel",
    name: "Microsoft Sentinel",
    vendor: "Microsoft",
    category: "siem",
    status: "disconnected",
    apiStatus: "unknown",
    endpoint: "",
    version: "—",
    description: "Cloud-native SIEM adapter for identity and cloud-plane detections.",
    adapterId: "sentinel",
    configFields: [
      { key: "tenantId", label: "Tenant ID", placeholder: "00000000-0000-0000-0000-000000000000" },
      { key: "clientSecret", label: "Client secret", placeholder: "••••••••", secret: true },
    ],
  },
  {
    id: "int-custom",
    name: "Custom Integration",
    vendor: "In-house",
    category: "response",
    status: "disconnected",
    apiStatus: "unknown",
    endpoint: "",
    version: "—",
    description: "Generic webhook adapter for any emulation, SIEM or response tool that can speak the Burhan schema.",
    adapterId: "custom",
    configFields: [
      { key: "webhookUrl", label: "Webhook URL", placeholder: "https://burhan.local/api/ingest" },
      { key: "token", label: "Shared secret", placeholder: "••••••••", secret: true },
    ],
  },
];

export const ANALYSTS = ["Y. Mansour", "S. Rahman", "K. Okafor"] as const;
